version: '3.9'

services:
  antiFloodGuardDbDev:
    image: postgres:15-alpine
    stop_signal: SIGINT
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    volumes:
      - ./db_data:/var/lib/postgresql/data
