version: '3.9'

services:
  db:
    image: postgres:15-alpine
    container_name: "anti-flood-guard-db"
    stop_signal: SIGINT
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    volumes:
      - ./db_data:/var/lib/postgresql/data
    networks:
      - tg_bot

  bot:
    container_name: "anti-flood-guard-bot"
    depends_on:
      - db
    stop_signal: SIGINT
    build:
      context: .
    working_dir: "/usr/src/app/${BOT_NAME}"
    volumes:
      - .:/usr/src/app/${BOT_NAME}
    command: python3 -m bot
    restart: always
    networks:
      - tg_bot

networks:
  tg_bot:
    driver: bridge
