"""tariff-free-fix

Revision ID: 138fb9f036fa
Revises: 11a8c3598c19
Create Date: 2023-08-30 10:24:23.587757

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '138fb9f036fa'
down_revision: Union[str, None] = '11a8c3598c19'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tariffs', 'free')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tariffs', sa.Column('free', sa.BOOLEAN(), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
