"""client-chat-id-fix

Revision ID: 5aa596257452
Revises: 138fb9f036fa
Create Date: 2023-08-30 18:27:52.485120

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5aa596257452'
down_revision: Union[str, None] = '138fb9f036fa'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user_tg_group_bots', 'group_id',
               existing_type=sa.VARCHAR(),
               type_=sa.BIGINT(),
               existing_nullable=False,
               postgresql_using='group_id::bigint')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user_tg_group_bots', 'group_id',
               existing_type=sa.BIGINT(),
               type_=sa.VARCHAR(),
               existing_nullable=False)
    # ### end Alembic commands ###
