"""admin-bots-add

Revision ID: 60ccb501dab6
Revises: 
Create Date: 2023-09-02 16:43:21.128900

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '60ccb501dab6'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('admin_group_bots',
    sa.Column('group_id', sa.BIGINT(), nullable=False),
    sa.Column('bot_settings', sa.JSON(), nullable=False),
    sa.PrimaryKeyConstraint('group_id', name=op.f('pk_admin_group_bots'))
    )
    op.create_table('bot_clients',
    sa.Column('tg_id', sa.BIGINT(), nullable=False),
    sa.Column('username', sa.String(), nullable=True),
    sa.Column('full_name', sa.String(), server_default='Пользователь', nullable=False),
    sa.PrimaryKeyConstraint('tg_id', name=op.f('pk_bot_clients'))
    )
    op.create_table('tariffs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('sum', sa.Integer(), nullable=False),
    sa.Column('limitation_days', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_tariffs')),
    sa.UniqueConstraint('name', name=op.f('uq_tariffs_name'))
    )
    op.create_table('client_subscribe',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('group_id', sa.BIGINT(), nullable=False),
    sa.Column('client_id', sa.BIGINT(), nullable=False),
    sa.Column('tariff_id', sa.Integer(), nullable=False),
    sa.Column('expire_date', sa.DateTime(), nullable=False),
    sa.Column('bot_settings', sa.JSON(), nullable=False),
    sa.Column('first_time_use', sa.Boolean(), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['client_id'], ['bot_clients.tg_id'], name=op.f('fk_client_subscribe_client_id_bot_clients')),
    sa.ForeignKeyConstraint(['tariff_id'], ['tariffs.id'], name=op.f('fk_client_subscribe_tariff_id_tariffs')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_client_subscribe')),
    sa.UniqueConstraint('client_id', 'tariff_id', 'group_id', name=op.f('uq_client_subscribe_client_id'))
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('client_subscribe')
    op.drop_table('tariffs')
    op.drop_table('bot_clients')
    op.drop_table('admin_group_bots')
    # ### end Alembic commands ###
