"""user-full-name

Revision ID: a538fac6bc87
Revises: 4a25c2bac6ad
Create Date: 2023-08-31 15:14:38.400929

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a538fac6bc87'
down_revision: Union[str, None] = '4a25c2bac6ad'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('bot_clients', sa.Column('full_name', sa.String(), server_default='Пользователь', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('bot_clients', 'full_name')
    # ### end Alembic commands ###
