"""add-admin-id

Revision ID: d12a3aa4933f
Revises: 60ccb501dab6
Create Date: 2023-09-02 17:21:55.534460

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd12a3aa4933f'
down_revision: Union[str, None] = '60ccb501dab6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('admin_group_bots', sa.Column('admin_id', sa.BIGINT(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('admin_group_bots', 'admin_id')
    # ### end Alembic commands ###
